### ISSUE TITLE
Not Open Source, Just a Sample?

### ISSUE THREAD

**Issue by johnwatsondev** [NewtronLabs/SharedMemory#2]

**Comment by NewtronLabs** [comment]
Hi @johnwatsondev!

The Shared Memory library is a free to use community outreach software developed by Newtron Labs. The library source code is not open source, yet you are allowed to use it for your own projects as long as you do not tamper with the source code, reverse engineer, decompile, etc. Please read the License here on the Github page for more information. 

We are here to help. Let us know if you have any other questions. 

Take care, 
Newtron Labs 
Community Outreach Program
