### ISSUE TITLE
getDefaultAdapter() throws java.lang.RuntimeException: Stub!

### ISSUE THREAD

**Issue by NoHarmDan** [NewtronLabs/SharedMemory#3]
Hi,
The issue is very simple as explained in the title - the `RemoteMemoryAdapter.getDefaultAdapter() `method does nothing other but throws a `RuntimeException`. Am I missing something?

Also, in the readme, you forgot to include `remoteMemory.readBytes(bytes, 0, 0, bytes.length);` in the part about the consumer. Though the examples are very clear about that. What they aren't clear about is what happens to the bytes already present in the memory, if I reuse it and say write a smaller amount of bytes. Does the remainder of the old ones stay there?

**Comment by NewtronLabs** [comment]
Hi @NoHarmDan!

For the exception it looks like you are not using `compileOnly.` Please double check that you are using this line: `compileOnly 'com.newtronlabs.sharedmemory:sharedmemory:2.0.0'`

For the other point. Yes, if you write fewer bytes than the size of the buffer then the remaining bytes will be the old ones. 

I hope that helps you; please feel free to reach out if you have more questions or run into any issues.

Thanks,
Newtron Labs
