### ISSUE TITLE
read failed: EACCES (Permission denied)in sdk 28

### ISSUE THREAD

**Issue by slee8789** [NewtronLabs/SharedMemory#4]
Playit wants sdk version 28 and up.

28 or later setting results in a read failed : Permission denied (EACCES) error. Are you aware of this issue?

**Comment by NewtronLabs** [comment]
Hi @slee8789!

We tried to reproduce the issue but where unable to replicate it. Could you share with us an MRE? Also what device are you testing this on?

Thanks,
Amy

**Comment by NewtronLabs** [comment]
Close for lack of activity.
