### ISSUE TITLE
POM file not found when trying to add to Android Studio

### ISSUE THREAD

**Issue by febryanasaperdana** [NewtronLabs/SharedMemory#6]
Hi, it looks like there's no valid POM file provided. Gradle can't find newtronlabs-android plugin POM file, as well as the dependency. Please fix it. Need this library ASAP.

**Comment by NewtronLabs** [comment]
Hi @febryanasaperdana,

Please provide your gradle file. We believe that you may not be configuring the dependency correctly. 

Thanks,
Amy

**Comment by febryanasaperdana** [comment]
`Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        jcenter()
        flatDir {
            dirs 'libs'
        }
        maven { url "http://code.newtronlabs.com:8081/artifactory/libs-release-local" }

    }
    dependencies {
        classpath "com.android.tools.build:gradle:4.0.2"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.21"
        classpath "org.jetbrains.kotlin:kotlin-android-extensions:1.4.21"
        classpath 'org.ow2.asm:asm:8.0.1'
        classpath 'org.ow2.asm:asm-util:8.0.1'
        classpath 'org.ow2.asm:asm-commons:8.0.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath 'com.newtronlabs.android:plugin:4.0.0'

    }
}

allprojects {
    repositories {
        google()
        jcenter()
        flatDir {
            dirs 'libs'
        }
        maven { url "http://code.newtronlabs.com:8081/artifactory/libs-release-local" }
    }
}


task clean(type: Delete) {
    delete rootProject.buildDir
}`

I follow the instruction properly, but it looks like the error is on your side (on your server, particularly the maven repo server that serves the library), not me.

**Comment by febryanasaperdana** [comment]
I think it's wrong on your side, could you check whether you can embed your library on android studio project?
This is the error I discovered from the build output:
Could not find com.newtronlabs.android:plugin:4.0.0.
Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/com/newtronlabs/android/plugin/4.0.0/plugin-4.0.0.pom
  - https://jcenter.bintray.com/com/newtronlabs/android/plugin/4.0.0/plugin-4.0.0.pom
  - http://code.newtronlabs.com:8081/artifactory/libs-release-local/com/newtronlabs/android/plugin/4.0.0/plugin-4.0.0.pom
Required by:
    project :

**Comment by febryanasaperdana** [comment]
closed due to slow response
