### ISSUE TITLE
My I ask some details

### ISSUE THREAD

**Issue by zongren** [NewtronLabs/SharedMemory#8]
Is this library built on MemoryFile?If so, how does it pass file descriptor between processes?

**Comment by NewtronLabs** [comment]
Hi @zongren,

We appreciate your interest in our software solution. And although we firmly believe in helping out the tech community we cannot share proprietary information without a commercial license. If you are interested in licensing our product please reach out through our website: www.newtronlabs.com

Cheers,
Amy

**Comment by zongren** [comment]
ok, I see, thanks anyway
