### ISSUE TITLE
support of new versions of gradle ?

### ISSUE THREAD

**Issue by FatimaZahra-FCH** [NewtronLabs/SharedMemory#9]
Hi, I want to know if there will be support for new versions of gradle and when ?

**Comment by NewtronLabs** [comment]
Hi @FatimaZahra-FCH,

The lead for our Community Outreach libraries worked over the weekend to upgrade the version. Please check the latest `README.md` for a version that will work with `gradle 7.0.4`. We hope that you enjoy.

Cheers,
Amy
